### ISSUE TITLE
Bot crash on PokeAlarm Mention

### ISSUE THREAD

**Issue by drunkenslang** [dandesousa/discord-raid-coordinator#23]
I am trying to start a separate channel when a raid starts.  If I use PokeAlarm to mention the coordinator role the bot crashes.  If I mention the role manually it's fine.  It seems like it is due to the PokeAlarm not having an actual name/link/profile.

**Comment by dandesousa** [comment]
Do you have the stack trace from the crash? Is this being done through a web-hook?

**Comment by drunkenslang** [comment]
I'm sorry it took so long to reply.  Yes it is being done through a webhook and I do not have a stack trace.  I can try to get you one when I have time if it will help.  Thanks

**Comment by dandesousa** [comment]
no need I was able to reproduce -- thanks

**Comment by drunkenslang** [comment]
Where can I change organizer role name?  I want to use different from @raid-organizer
I see in your help page that there is @raid-lugia used.  Thanks for the great bot

**Comment by dandesousa** [comment]
https://github.com/dandesousa/discord-raid-coordinator/blob/master/src/raid_coordinator/bot.py#L705

**Comment by drunkenslang** [comment]
Thank you very much.  I hope you can solve the Pokealarm crashing then this will work awesome for what we need it for

**Comment by dandesousa** [comment]
It should work now -- test this manually for webhooks -- latest release 0.3.1 should have that fix

**Comment by dandesousa** [comment]
forgot to push the tag but its in master and pypi

**Comment by drunkenslang** [comment]
I tried it last night and it still crashed.  I used it from GitHub Master

**Comment by drunkenslang** [comment]
I'll try again later

**Comment by dandesousa** [comment]
I think I'll need more details, like the stack trace from the crash

**Comment by dandesousa** [comment]
Also the way in which your webhook is configured for reproducibility.

**Comment by drunkenslang** [comment]
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "c:\python36\lib\site-packages\raid_coordinator\bot.py", line 599, in on_message
    raid_channel = await start_raid_group(user, raid_message, message.clean_content)
  File "c:\python36\lib\site-packages\raid_coordinator\bot.py", line 331, in start_raid_group
    server = user.server
AttributeError: 'User' object has no attribute 'server'
Ignoring exception in on_message
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "c:\python36\lib\site-packages\raid_coordinator\bot.py", line 599, in on_message
    raid_channel = await start_raid_group(user, raid_message, message.clean_content)
  File "c:\python36\lib\site-packages\raid_coordinator\bot.py", line 331, in start_raid_group
    server = user.server
AttributeError: 'User' object has no attribute 'server'

**Comment by drunkenslang** [comment]
"raid": {
			"webhook_url": "https://discordapp.com/api/webhooks/347444431978496002/a3qTVjY0O342fsdg435345nVPFMM41DsHP5j76aysBvGw2iSvnBOQdtQviq0tG_N",
			"username": "<pkmn> Raid",
			"icon_url": "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/<pkmn_id>.png",
			"title": "<city>/<gym_name>",
			"url": "<gmaps>",
			"body": " Raid will end at <12h_time> (<time_left>). <quick_move>/<charge_move>",
			"content": "<@&347434657748875>",
			"map":  {
				"enable":"true",
				"width": "250",
				"height": "125",
				"maptype": "roadmap",
				"zoom": "15"

**Comment by dandesousa** [comment]
That issue has been resolved. Pull Master, restart and try again. We no longer use the user to get the server reference.

**Comment by dandesousa** [comment]
Are you sure you aren't using a fixed version? Trying pulling 0.3.0 from pypi

**Comment by drunkenslang** [comment]
I did a git pull last night but won't have time to test for a few days

**Comment by dandesousa** [comment]
Yeah just verify the install -- code you ran is not in current master. Run
`pip freeze` when you get a chance to report the version

**Comment by drunkenslang** [comment]
aiohttp==1.0.5
async-timeout==1.2.1
chardet==3.0.4
discord-raid-coordinator==0.2.0
discord.py==0.16.8
multidict==3.1.3
pytz==2017.2
websockets==3.3

I swear i ran git pull from Master but that isn<t correct version shown is it

**Comment by dandesousa** [comment]
looks like you have it installed so you will need to upgrade your environment. Need to be on `0.3.2`

**Comment by drunkenslang** [comment]
aww my bad I did pip install after git pull.  i uninstalled then installed now its on correct version.  Ill try it when i get home.   Im on remote desktop on my phone right now and it sucks.  its there an upgrade command^

**Comment by dandesousa** [comment]
`pip install -U <package>==<version>`

**Comment by drunkenslang** [comment]
Works great now
